#!/bin/bash
set -e

export ARCH=${ARCH:-"amd64"}
BASE=images

source $(dirname $0)/version
cd $(dirname $0)/..

mkdir -p dist
> dist/images

for i in $BASE/[1-9]*; do
    name="os-$(echo ${i} | cut -f2 -d-)"

    IFS='-' read -ra dirname <<< "$i"
    version=${dirname[2]}
    tag="${OS_REPO}/${name}:${version}${SUFFIX}"

    echo Building ${tag}
    if [ -e ${i}/prebuild.sh ]; then
        ${i}/prebuild.sh
    fi

    if dapper -d --build -f ${i}/Dockerfile -- -t rancher/${name} ${i}; then
        docker tag rancher/${name} ${tag}
        echo ${tag} >> dist/images
    elif [ "$?" != "42" ]; then
        exit 1
    else
        echo "Skipping ${tag}"
    fi
done

